name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: download code
        uses: actions/checkout@v6

      - name: install Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: compilation and test
        run: mvn --batch-mode clean verify

      - name: save JAR
        uses: actions/upload-artifact@v4
        with:
          name: relationship-manager
          path: target/*.jar
          if-no-files-found: error
